### ISSUE TITLE
The library is handing

### ISSUE THREAD

**Issue by ivan-zapreev** [Turbine1991/cpp-feather-ini-parser#3]
The config file parsing is hanging in case the line length exceeds the 128 bytes length specified as the value of FINI_BUFFER_SIZE. Increase the buffer size to make it more practical or change the way the config file is read to prevent hanging.

**Comment by Turbine1991** [comment]
Good catch. I'll make sure to change the way it handles reading lines into the buffer to avoid hangs. The result will be truncated data.
