### ISSUE TITLE
the project need object enumeration support ?

### ISSUE THREAD

**Issue by R415** [Turbine1991/cpp-feather-ini-parser#4]
the library does not have a function to list section 
no function to list items of section.
how about deque style access for spesific nth item ie ini[0] to access #0th elements name may be.
and how about listing of spesific sections items only which microsofts implementation has but is not cross platform directly so it too is useless alot.

**Comment by Turbine1991** [comment]
Sure it does. You can loop through every key of every section. Look at the example script!

**Comment by Turbine1991** [comment]
Just use the data-structure functionality directly. :)

**Comment by R415** [comment]
ini.sections.size()  i can use this but getting the sections or section doesnt work. 
i tryed something like this  
cout << ini.sections[0] but didnt work .
how can i access the contents of elements ?

another topic but is how is the duble contents checked ? 
do we have to implement it or is there a mechanism that checks double contents and searchs for copies of it ?

**Comment by Turbine1991** [comment]
Remember every section has a series of keys in an INI file. In your message your using "cout" to print out the contents of an "unsorted_map". They are not stored in an array which is indexable via a single value.

Manually referencing section/jey:
`std::cout << ini["section1"]["key1"];`

If you really want to access them with a numeric index, you can do this. Make your INI section data type int and changing the sections to reflect a numeric value, like so:

Example file - example.ini:
`
[0]
key1=abc
key2=def
[1]
key3=ghi
[2]
key4=jkl
`

Example code:
`
typedef INI<int, std::string, std::string> ini_t;
ini_t ini("example.ini", true);

std::cout << ini[0]["key1"]; //Prints "abc"
std::cout << ini[1]["key3"]; //Prints "ghi"
std::cout << ini[2]["key4"]; //Prints "ghi"
`

Here's how to iterate (loop through all sections and keys):
`
   for(auto i = ini.sections.begin(); i != ini.sections.end(); i++)
   {
      //Section name as ini_t::section_t
      cout << i->first << endl;

      if (i->second->size() == 0)  //No keys/values in section, skip to next
         continue;

      for(auto j = i->second->begin(); j != i->second->end(); j++)
      {
         //Name as ini_t::key_t & Value as ini_t::key_t
         cout << " " << j->first << "=" << j->second << endl;
      }
   }
`

**Comment by Turbine1991** [comment]
"another topic but how is the duble contents checked ? 
do we have to implement it or is there a mechanism that checks double contents and searchs for copies of it ?"

This would mean a duplicate section. This is something I considered. The way you'd access these would be by iterating through the key/value pairs as provided in the prior post.
