### ISSUE TITLE
parse()'s reading logic flawed

### ISSUE THREAD

**Issue by TheAssassin** [Turbine1991/cpp-feather-ini-parser#8]
Take this file as an example:

```ini
[Desktop Entry]
Version=1.0
Type=Application
Name=Strawberry
GenericName=Strawberry Music Player
Comment=Plays music
Exec=strawberry %U
TryExec=strawberry
Icon=strawberry
Terminal=false
Categories=AudioVideo;Player;Qt;Audio;
StartupNotify=false
MimeType=x-content/audio-player;application/ogg;application/x-ogg;application/x-ogm-audio;audio/flac;audio/aac;audio/mp4;audio/mpeg;audio/mpegurl;audio/ogg;audio/vorbis;audio/vnd.rn-realaudio;audio/x-wav;audio/x-flac;audio/x-oggflac;audio/x-vorbis;audio/x-vorbis+ogg;audio/x-mp3;audio/x-mpeg;audio/x-mpegurl;audio/x-ms-wma;audio/x-musepack;audio/x-pn-realaudio;audio/x-scpls;audio/x-speex;video/x-ms-asf;
```

It's a perfectly valid desktop file (and therefore ini file), however cpp-feather-ini-parser's `parse()` function will get stuck in an infinite loop while trying to read that file's last line.

While looking into this within the scope of https://github.com/linuxdeploy/linuxdeploy/issues/39, it turned out that the [line buffer size](https://github.com/linuxdeploy/linuxdeploy/issues/39) is too small, causing the reading loop to break.

You shouldn't "assume" a maximum line size, that's never a good idea. Instead, the lines should be parsed using e.g., `std::getline(istream& is, string& line)`, which will read characters into `line` until a newline character is found. That way, a buffer size doesn't have to be assumed, and files with very long lines will be parsed just fine. It might be slightly slower, but I don't think that this matters. Also, it'll be more memory efficient.

Just replace `fini_char_t line[FINI_BUFFER_SIZE]; while(!file.eof()) {...}` with `std::string line; while (std::getline(file, line)) {...}`. You could probably also use a `vector<your_char_t>` and the C version of `getline()`, or a `std::wstring`.

**Comment by Turbine1991** [comment]
I've planning to reprogram this library using std::string in the future and make a few simplifications. You're absolutely right, I should have used the string syntax.

**Comment by TheAssassin** [comment]
I wrote my own parser for now. As you should know now, my domain is working with desktop files. They're very similar to INI files, they basically just add a few constraints on top of the INI format.

I wrote my own parser for now, which is less complex in using, quite fast, and nearly completely tested. See https://github.com/linuxdeploy/linuxdeploy/tree/master/src/core/desktopfile. So far, it doesn't perform any desktop file specific actions, but that will be introduced quite soon, after extracting it from linuxdeploy into a separate library. 

Perhaps you can find some inspiration in there, or you want to collaborate on developing a single project.

**Comment by Turbine1991** [comment]
I've finally re-written this parser. Everything has been addressed.

There are no line length limits.

The following is now parsed without errors:
-Comments (// and #)
-Semi-colons at the end of a key value pair
-Indentation

The following may be applied when saving:
-Pruning empty sections/keys value pairs
-Padding between section blocks
-Spaces around section value
-Spaces inside key value pairs
-Indented key value pairs
-Semicolons appended to key value pairs
